# Generated by Django 5.0.6 on 2024-07-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
